# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '200815_Integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 200815_Integration
pod 'FirebaseUI'
pod 'FoldingCell'
pod 'XLPagerTabStrip'
pod "Gemini"
pod 'FoldingCell'




end
