# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '200814_login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 200814_login
pod 'FirebaseUI'

end
