# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toppage_ver_1.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for toppage_ver_1.0


source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
pod 'TimelineTableViewCell'


end
