# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2nd_FoldingCell_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2nd_FoldingCell_demo
pod 'FoldingCell'

end
